window.esdocSearchIndex = [
  [
    "bricklink-api/src/catalogitem/catalogitem.js~catalogitem",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html",
    "<span>CatalogItem</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/catalogItem.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/client.js~client",
    "class/src/client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">bricklink-api/src/client.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/condition.js~condition",
    "class/src/condition.js~Condition.html",
    "<span>Condition</span> <span class=\"search-result-import-path\">bricklink-api/src/condition.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/itemimage.js~itemimage",
    "class/src/catalogItem/itemImage.js~ItemImage.html",
    "<span>ItemImage</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/itemImage.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/itemtype.js~itemtype",
    "class/src/itemType.js~ItemType.html",
    "<span>ItemType</span> <span class=\"search-result-import-path\">bricklink-api/src/itemType.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/knowncolor.js~knowncolor",
    "class/src/catalogItem/knownColor.js~KnownColor.html",
    "<span>KnownColor</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/knownColor.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/oauthhelper.js~oauthhelper",
    "class/src/oAuthHelper.js~OAuthHelper.html",
    "<span>OAuthHelper</span> <span class=\"search-result-import-path\">bricklink-api/src/oAuthHelper.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/priceguide.js~pricedetail",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html",
    "<span>PriceDetail</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/priceGuide.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/priceguide.js~priceguide",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html",
    "<span>PriceGuide</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/priceGuide.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/priceguide.js~priceguideoptions",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html",
    "<span>PriceGuideOptions</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/priceGuide.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/request.js~request",
    "class/src/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">bricklink-api/src/request.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/request.js~requestparams",
    "class/src/request.js~RequestParams.html",
    "<span>RequestParams</span> <span class=\"search-result-import-path\">bricklink-api/src/request.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/subsets.js~subset",
    "class/src/catalogItem/subsets.js~Subset.html",
    "<span>Subset</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/subsets.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/subsets.js~subsetentry",
    "class/src/catalogItem/subsets.js~SubsetEntry.html",
    "<span>SubsetEntry</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/subsets.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/subsets.js~subsetoptions",
    "class/src/catalogItem/subsets.js~SubsetOptions.html",
    "<span>SubsetOptions</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/subsets.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/supersets.js~superset",
    "class/src/catalogItem/supersets.js~Superset.html",
    "<span>Superset</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/supersets.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/supersets.js~supersetentry",
    "class/src/catalogItem/supersets.js~SupersetEntry.html",
    "<span>SupersetEntry</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/supersets.js</span>",
    "class"
  ],
  [
    "bricklink-api/src/catalogitem/supersets.js~supersetoptions",
    "class/src/catalogItem/supersets.js~SupersetOptions.html",
    "<span>SupersetOptions</span> <span class=\"search-result-import-path\">bricklink-api/src/catalogItem/supersets.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/catalogitem/catalogitem.js",
    "file/src/catalogItem/catalogItem.js.html",
    "src/catalogItem/catalogItem.js",
    "file"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#alternate_no",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-alternate_no",
    "src/catalogItem/catalogItem.js~CatalogItem#alternate_no",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#category_id",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-category_id",
    "src/catalogItem/catalogItem.js~CatalogItem#category_id",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#constructor",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-constructor-constructor",
    "src/catalogItem/catalogItem.js~CatalogItem#constructor",
    "method"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#description",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-description",
    "src/catalogItem/catalogItem.js~CatalogItem#description",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#dim_x",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-dim_x",
    "src/catalogItem/catalogItem.js~CatalogItem#dim_x",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#dim_y",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-dim_y",
    "src/catalogItem/catalogItem.js~CatalogItem#dim_y",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#dim_z",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-dim_z",
    "src/catalogItem/catalogItem.js~CatalogItem#dim_z",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#image_url",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-image_url",
    "src/catalogItem/catalogItem.js~CatalogItem#image_url",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#is_obsolete",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-is_obsolete",
    "src/catalogItem/catalogItem.js~CatalogItem#is_obsolete",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#language_code",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-language_code",
    "src/catalogItem/catalogItem.js~CatalogItem#language_code",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#name",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-name",
    "src/catalogItem/catalogItem.js~CatalogItem#name",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#no",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-no",
    "src/catalogItem/catalogItem.js~CatalogItem#no",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#thumbnail_url",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-thumbnail_url",
    "src/catalogItem/catalogItem.js~CatalogItem#thumbnail_url",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#type",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-type",
    "src/catalogItem/catalogItem.js~CatalogItem#type",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#weight",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-weight",
    "src/catalogItem/catalogItem.js~CatalogItem#weight",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem#year_released",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#instance-member-year_released",
    "src/catalogItem/catalogItem.js~CatalogItem#year_released",
    "member"
  ],
  [
    "src/catalogitem/catalogitem.js~catalogitem.get",
    "class/src/catalogItem/catalogItem.js~CatalogItem.html#static-method-get",
    "src/catalogItem/catalogItem.js~CatalogItem.get",
    "method"
  ],
  [
    "src/catalogitem/itemimage.js",
    "file/src/catalogItem/itemImage.js.html",
    "src/catalogItem/itemImage.js",
    "file"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage#color_id",
    "class/src/catalogItem/itemImage.js~ItemImage.html#instance-member-color_id",
    "src/catalogItem/itemImage.js~ItemImage#color_id",
    "member"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage#constructor",
    "class/src/catalogItem/itemImage.js~ItemImage.html#instance-constructor-constructor",
    "src/catalogItem/itemImage.js~ItemImage#constructor",
    "method"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage#no",
    "class/src/catalogItem/itemImage.js~ItemImage.html#instance-member-no",
    "src/catalogItem/itemImage.js~ItemImage#no",
    "member"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage#thumbnail_url",
    "class/src/catalogItem/itemImage.js~ItemImage.html#instance-member-thumbnail_url",
    "src/catalogItem/itemImage.js~ItemImage#thumbnail_url",
    "member"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage#type",
    "class/src/catalogItem/itemImage.js~ItemImage.html#instance-member-type",
    "src/catalogItem/itemImage.js~ItemImage#type",
    "member"
  ],
  [
    "src/catalogitem/itemimage.js~itemimage.get",
    "class/src/catalogItem/itemImage.js~ItemImage.html#static-method-get",
    "src/catalogItem/itemImage.js~ItemImage.get",
    "method"
  ],
  [
    "src/catalogitem/knowncolor.js",
    "file/src/catalogItem/knownColor.js.html",
    "src/catalogItem/knownColor.js",
    "file"
  ],
  [
    "src/catalogitem/knowncolor.js~knowncolor#color_id",
    "class/src/catalogItem/knownColor.js~KnownColor.html#instance-member-color_id",
    "src/catalogItem/knownColor.js~KnownColor#color_id",
    "member"
  ],
  [
    "src/catalogitem/knowncolor.js~knowncolor#constructor",
    "class/src/catalogItem/knownColor.js~KnownColor.html#instance-constructor-constructor",
    "src/catalogItem/knownColor.js~KnownColor#constructor",
    "method"
  ],
  [
    "src/catalogitem/knowncolor.js~knowncolor#quantity",
    "class/src/catalogItem/knownColor.js~KnownColor.html#instance-member-quantity",
    "src/catalogItem/knownColor.js~KnownColor#quantity",
    "member"
  ],
  [
    "src/catalogitem/knowncolor.js~knowncolor.get",
    "class/src/catalogItem/knownColor.js~KnownColor.html#static-method-get",
    "src/catalogItem/knownColor.js~KnownColor.get",
    "method"
  ],
  [
    "src/catalogitem/priceguide.js",
    "file/src/catalogItem/priceGuide.js.html",
    "src/catalogItem/priceGuide.js",
    "file"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#buyer_country_code",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-buyer_country_code",
    "src/catalogItem/priceGuide.js~PriceDetail#buyer_country_code",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#constructor",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-constructor-constructor",
    "src/catalogItem/priceGuide.js~PriceDetail#constructor",
    "method"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#date_ordered",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-date_ordered",
    "src/catalogItem/priceGuide.js~PriceDetail#date_ordered",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#quantity",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-quantity",
    "src/catalogItem/priceGuide.js~PriceDetail#quantity",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#seller_country_code",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-seller_country_code",
    "src/catalogItem/priceGuide.js~PriceDetail#seller_country_code",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#shipping_available",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-shipping_available",
    "src/catalogItem/priceGuide.js~PriceDetail#shipping_available",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~pricedetail#unit_price",
    "class/src/catalogItem/priceGuide.js~PriceDetail.html#instance-member-unit_price",
    "src/catalogItem/priceGuide.js~PriceDetail#unit_price",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#avg_price",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-avg_price",
    "src/catalogItem/priceGuide.js~PriceGuide#avg_price",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#constructor",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-constructor-constructor",
    "src/catalogItem/priceGuide.js~PriceGuide#constructor",
    "method"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#currency_code",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-currency_code",
    "src/catalogItem/priceGuide.js~PriceGuide#currency_code",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#item",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-item",
    "src/catalogItem/priceGuide.js~PriceGuide#item",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#max_price",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-max_price",
    "src/catalogItem/priceGuide.js~PriceGuide#max_price",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#min_price",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-min_price",
    "src/catalogItem/priceGuide.js~PriceGuide#min_price",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#new_or_used",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-new_or_used",
    "src/catalogItem/priceGuide.js~PriceGuide#new_or_used",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#price_detail",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-price_detail",
    "src/catalogItem/priceGuide.js~PriceGuide#price_detail",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#qty_avg_price",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-qty_avg_price",
    "src/catalogItem/priceGuide.js~PriceGuide#qty_avg_price",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#total_quantity",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-total_quantity",
    "src/catalogItem/priceGuide.js~PriceGuide#total_quantity",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide#unit_quantity",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#instance-member-unit_quantity",
    "src/catalogItem/priceGuide.js~PriceGuide#unit_quantity",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguide.get",
    "class/src/catalogItem/priceGuide.js~PriceGuide.html#static-method-get",
    "src/catalogItem/priceGuide.js~PriceGuide.get",
    "method"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#color_id",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-color_id",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#color_id",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#constructor",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-constructor-constructor",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#constructor",
    "method"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#country_code",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-country_code",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#country_code",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#currency_code",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-currency_code",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#currency_code",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#guide_type",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-guide_type",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#guide_type",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#new_or_used",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-new_or_used",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#new_or_used",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#region",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-region",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#region",
    "member"
  ],
  [
    "src/catalogitem/priceguide.js~priceguideoptions#vat",
    "class/src/catalogItem/priceGuide.js~PriceGuideOptions.html#instance-member-vat",
    "src/catalogItem/priceGuide.js~PriceGuideOptions#vat",
    "member"
  ],
  [
    "src/catalogitem/subsets.js",
    "file/src/catalogItem/subsets.js.html",
    "src/catalogItem/subsets.js",
    "file"
  ],
  [
    "src/catalogitem/subsets.js~subset#constructor",
    "class/src/catalogItem/subsets.js~Subset.html#instance-constructor-constructor",
    "src/catalogItem/subsets.js~Subset#constructor",
    "method"
  ],
  [
    "src/catalogitem/subsets.js~subset#entries",
    "class/src/catalogItem/subsets.js~Subset.html#instance-member-entries",
    "src/catalogItem/subsets.js~Subset#entries",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subset#match_no",
    "class/src/catalogItem/subsets.js~Subset.html#instance-member-match_no",
    "src/catalogItem/subsets.js~Subset#match_no",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subset.get",
    "class/src/catalogItem/subsets.js~Subset.html#static-method-get",
    "src/catalogItem/subsets.js~Subset.get",
    "method"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#color_id",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-member-color_id",
    "src/catalogItem/subsets.js~SubsetEntry#color_id",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#constructor",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-constructor-constructor",
    "src/catalogItem/subsets.js~SubsetEntry#constructor",
    "method"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#extra_quantity",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-member-extra_quantity",
    "src/catalogItem/subsets.js~SubsetEntry#extra_quantity",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#is_alternate",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-member-is_alternate",
    "src/catalogItem/subsets.js~SubsetEntry#is_alternate",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#item",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-member-item",
    "src/catalogItem/subsets.js~SubsetEntry#item",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetentry#quantity",
    "class/src/catalogItem/subsets.js~SubsetEntry.html#instance-member-quantity",
    "src/catalogItem/subsets.js~SubsetEntry#quantity",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#box",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-member-box",
    "src/catalogItem/subsets.js~SubsetOptions#box",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#break_minifigs",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-member-break_minifigs",
    "src/catalogItem/subsets.js~SubsetOptions#break_minifigs",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#break_subsets",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-member-break_subsets",
    "src/catalogItem/subsets.js~SubsetOptions#break_subsets",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#color_id",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-member-color_id",
    "src/catalogItem/subsets.js~SubsetOptions#color_id",
    "member"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#constructor",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-constructor-constructor",
    "src/catalogItem/subsets.js~SubsetOptions#constructor",
    "method"
  ],
  [
    "src/catalogitem/subsets.js~subsetoptions#instruction",
    "class/src/catalogItem/subsets.js~SubsetOptions.html#instance-member-instruction",
    "src/catalogItem/subsets.js~SubsetOptions#instruction",
    "member"
  ],
  [
    "src/catalogitem/supersets.js",
    "file/src/catalogItem/supersets.js.html",
    "src/catalogItem/supersets.js",
    "file"
  ],
  [
    "src/catalogitem/supersets.js~superset#color_id",
    "class/src/catalogItem/supersets.js~Superset.html#instance-member-color_id",
    "src/catalogItem/supersets.js~Superset#color_id",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~superset#constructor",
    "class/src/catalogItem/supersets.js~Superset.html#instance-constructor-constructor",
    "src/catalogItem/supersets.js~Superset#constructor",
    "method"
  ],
  [
    "src/catalogitem/supersets.js~superset#entries",
    "class/src/catalogItem/supersets.js~Superset.html#instance-member-entries",
    "src/catalogItem/supersets.js~Superset#entries",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~superset.get",
    "class/src/catalogItem/supersets.js~Superset.html#static-method-get",
    "src/catalogItem/supersets.js~Superset.get",
    "method"
  ],
  [
    "src/catalogitem/supersets.js~supersetentry#appear_as",
    "class/src/catalogItem/supersets.js~SupersetEntry.html#instance-member-appear_as",
    "src/catalogItem/supersets.js~SupersetEntry#appear_as",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~supersetentry#constructor",
    "class/src/catalogItem/supersets.js~SupersetEntry.html#instance-constructor-constructor",
    "src/catalogItem/supersets.js~SupersetEntry#constructor",
    "method"
  ],
  [
    "src/catalogitem/supersets.js~supersetentry#item",
    "class/src/catalogItem/supersets.js~SupersetEntry.html#instance-member-item",
    "src/catalogItem/supersets.js~SupersetEntry#item",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~supersetentry#quantity",
    "class/src/catalogItem/supersets.js~SupersetEntry.html#instance-member-quantity",
    "src/catalogItem/supersets.js~SupersetEntry#quantity",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~supersetoptions#color_id",
    "class/src/catalogItem/supersets.js~SupersetOptions.html#instance-member-color_id",
    "src/catalogItem/supersets.js~SupersetOptions#color_id",
    "member"
  ],
  [
    "src/catalogitem/supersets.js~supersetoptions#constructor",
    "class/src/catalogItem/supersets.js~SupersetOptions.html#instance-constructor-constructor",
    "src/catalogItem/supersets.js~SupersetOptions#constructor",
    "method"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~client#agent",
    "class/src/client.js~Client.html#instance-member-agent",
    "src/client.js~Client#agent",
    "member"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/client.js~Client.html#instance-constructor-constructor",
    "src/client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#consumer_key",
    "class/src/client.js~Client.html#instance-member-consumer_key",
    "src/client.js~Client#consumer_key",
    "member"
  ],
  [
    "src/client.js~client#consumer_secret",
    "class/src/client.js~Client.html#instance-member-consumer_secret",
    "src/client.js~Client#consumer_secret",
    "member"
  ],
  [
    "src/client.js~client#endpoint",
    "class/src/client.js~Client.html#instance-member-endpoint",
    "src/client.js~Client#endpoint",
    "member"
  ],
  [
    "src/client.js~client#getcatalogitem",
    "class/src/client.js~Client.html#instance-method-getCatalogItem",
    "src/client.js~Client#getCatalogItem",
    "method"
  ],
  [
    "src/client.js~client#getitemimage",
    "class/src/client.js~Client.html#instance-method-getItemImage",
    "src/client.js~Client#getItemImage",
    "method"
  ],
  [
    "src/client.js~client#getitemsubset",
    "class/src/client.js~Client.html#instance-method-getItemSubset",
    "src/client.js~Client#getItemSubset",
    "method"
  ],
  [
    "src/client.js~client#getitemsuperset",
    "class/src/client.js~Client.html#instance-method-getItemSuperset",
    "src/client.js~Client#getItemSuperset",
    "method"
  ],
  [
    "src/client.js~client#getknowncolors",
    "class/src/client.js~Client.html#instance-method-getKnownColors",
    "src/client.js~Client#getKnownColors",
    "method"
  ],
  [
    "src/client.js~client#getpriceguide",
    "class/src/client.js~Client.html#instance-method-getPriceGuide",
    "src/client.js~Client#getPriceGuide",
    "method"
  ],
  [
    "src/client.js~client#send",
    "class/src/client.js~Client.html#instance-method-send",
    "src/client.js~Client#send",
    "method"
  ],
  [
    "src/client.js~client#token",
    "class/src/client.js~Client.html#instance-member-token",
    "src/client.js~Client#token",
    "member"
  ],
  [
    "src/client.js~client#token_secret",
    "class/src/client.js~Client.html#instance-member-token_secret",
    "src/client.js~Client#token_secret",
    "member"
  ],
  [
    "src/condition.js",
    "file/src/condition.js.html",
    "src/condition.js",
    "file"
  ],
  [
    "src/condition.js~condition.new",
    "class/src/condition.js~Condition.html#static-get-New",
    "src/condition.js~Condition.New",
    "member"
  ],
  [
    "src/condition.js~condition.used",
    "class/src/condition.js~Condition.html#static-get-Used",
    "src/condition.js~Condition.Used",
    "member"
  ],
  [
    "src/itemtype.js",
    "file/src/itemType.js.html",
    "src/itemType.js",
    "file"
  ],
  [
    "src/itemtype.js~itemtype.book",
    "class/src/itemType.js~ItemType.html#static-get-Book",
    "src/itemType.js~ItemType.Book",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.box",
    "class/src/itemType.js~ItemType.html#static-get-Box",
    "src/itemType.js~ItemType.Box",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.catalog",
    "class/src/itemType.js~ItemType.html#static-get-Catalog",
    "src/itemType.js~ItemType.Catalog",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.gear",
    "class/src/itemType.js~ItemType.html#static-get-Gear",
    "src/itemType.js~ItemType.Gear",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.instruction",
    "class/src/itemType.js~ItemType.html#static-get-Instruction",
    "src/itemType.js~ItemType.Instruction",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.minifigure",
    "class/src/itemType.js~ItemType.html#static-get-Minifigure",
    "src/itemType.js~ItemType.Minifigure",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.part",
    "class/src/itemType.js~ItemType.html#static-get-Part",
    "src/itemType.js~ItemType.Part",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.set",
    "class/src/itemType.js~ItemType.html#static-get-Set",
    "src/itemType.js~ItemType.Set",
    "member"
  ],
  [
    "src/itemtype.js~itemtype.unsortedlot",
    "class/src/itemType.js~ItemType.html#static-get-UnsortedLot",
    "src/itemType.js~ItemType.UnsortedLot",
    "member"
  ],
  [
    "src/oauthhelper.js",
    "file/src/oAuthHelper.js.html",
    "src/oAuthHelper.js",
    "file"
  ],
  [
    "src/oauthhelper.js~oauthhelper#constructor",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-constructor-constructor",
    "src/oAuthHelper.js~OAuthHelper#constructor",
    "method"
  ],
  [
    "src/oauthhelper.js~oauthhelper#consumerkey",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-member-consumerKey",
    "src/oAuthHelper.js~OAuthHelper#consumerKey",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#header",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-get-header",
    "src/oAuthHelper.js~OAuthHelper#header",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#nonce",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-member-nonce",
    "src/oAuthHelper.js~OAuthHelper#nonce",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#parameters",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-get-parameters",
    "src/oAuthHelper.js~OAuthHelper#parameters",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#querystring",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-get-queryString",
    "src/oAuthHelper.js~OAuthHelper#queryString",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#sign",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-method-sign",
    "src/oAuthHelper.js~OAuthHelper#sign",
    "method"
  ],
  [
    "src/oauthhelper.js~oauthhelper#signature",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-member-signature",
    "src/oAuthHelper.js~OAuthHelper#signature",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#timestamp",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-member-timestamp",
    "src/oAuthHelper.js~OAuthHelper#timestamp",
    "member"
  ],
  [
    "src/oauthhelper.js~oauthhelper#token",
    "class/src/oAuthHelper.js~OAuthHelper.html#instance-member-token",
    "src/oAuthHelper.js~OAuthHelper#token",
    "member"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~request#callback",
    "class/src/request.js~Request.html#instance-member-callback",
    "src/request.js~Request#callback",
    "member"
  ],
  [
    "src/request.js~request#constructor",
    "class/src/request.js~Request.html#instance-constructor-constructor",
    "src/request.js~Request#constructor",
    "method"
  ],
  [
    "src/request.js~request#method",
    "class/src/request.js~Request.html#instance-member-method",
    "src/request.js~Request#method",
    "member"
  ],
  [
    "src/request.js~request#params",
    "class/src/request.js~Request.html#instance-member-params",
    "src/request.js~Request#params",
    "member"
  ],
  [
    "src/request.js~request#uri",
    "class/src/request.js~Request.html#instance-member-uri",
    "src/request.js~Request#uri",
    "member"
  ],
  [
    "src/request.js~request.delete",
    "class/src/request.js~Request.html#static-get-DELETE",
    "src/request.js~Request.DELETE",
    "member"
  ],
  [
    "src/request.js~request.get",
    "class/src/request.js~Request.html#static-get-GET",
    "src/request.js~Request.GET",
    "member"
  ],
  [
    "src/request.js~request.post",
    "class/src/request.js~Request.html#static-get-POST",
    "src/request.js~Request.POST",
    "member"
  ],
  [
    "src/request.js~request.put",
    "class/src/request.js~Request.html#static-get-PUT",
    "src/request.js~Request.PUT",
    "member"
  ],
  [
    "src/request.js~requestparams#toobject",
    "class/src/request.js~RequestParams.html#instance-method-toObject",
    "src/request.js~RequestParams#toObject",
    "method"
  ],
  [
    "src/request.js~requestparams#toquerystring",
    "class/src/request.js~RequestParams.html#instance-method-toQueryString",
    "src/request.js~RequestParams#toQueryString",
    "method"
  ]
]